#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  2 18:40:54 2022

@author: miadowns
"""
import matplotlib.pyplot as plt


count = 0



my_file = open("chapter_one.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter one")
print("creature occurs ", occurances_creature, "times in chapter one")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter one")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter one")
print("Ernest occurs ", occurances_ernest, "times in chapter one")
print("Felix occurs ", occurances_felix, "times in chapter one")
print("Henry occurs ", occurances_henry, "times in chapter one")
print("Justine occurs ", occurances_justine, "times in chapter one")
print("Victor occurs ", occurances_victor, "times in chapter one")
print("William occurs ", occurances_william, "times in chapter one")
print ("")

my_file = open("chapter_two.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter two")
print("creature occurs ", occurances_creature, "times in chapter two")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter two")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter two")
print("Ernest occurs ", occurances_ernest, "times in chapter two")
print("Felix occurs ", occurances_felix, "times in chapter two")
print("Henry occurs ", occurances_henry, "times in chapter two")
print("Justine occurs ", occurances_justine, "times in chapter two")
print("Victor occurs ", occurances_victor, "times in chapter two")
print("William occurs ", occurances_william, "times in chapter two")
print ("")

my_file = open("chapter_three.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter three")
print("creature occurs ", occurances_creature, "times in chapter three")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter three")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter three")
print("Ernest occurs ", occurances_ernest, "times in chapter three")
print("Felix occurs ", occurances_felix, "times in chapter three")
print("Henry occurs ", occurances_henry, "times in chapter three")
print("Justine occurs ", occurances_justine, "times in chapter three")
print("Victor occurs ", occurances_victor, "times in chapter three")
print("William occurs ", occurances_william, "times in chapter three")
print ("")

my_file = open("chapter_four.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter four")
print("creature occurs ", occurances_creature, "times in chapter four")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter four")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter four")
print("Ernest occurs ", occurances_ernest, "times in chapter four")
print("Felix occurs ", occurances_felix, "times in chapter four")
print("Henry occurs ", occurances_henry, "times in chapter four")
print("Justine occurs ", occurances_justine, "times in chapter four")
print("Victor occurs ", occurances_victor, "times in chapter four")
print("William occurs ", occurances_william, "times in chapter four")
print ("")

my_file = open("chapter_five.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter five")
print("creature occurs ", occurances_creature, "times in chapter five")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter five")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter five")
print("Ernest occurs ", occurances_ernest, "times in chapter five")
print("Felix occurs ", occurances_felix, "times in chapter five")
print("Henry occurs ", occurances_henry, "times in chapter five")
print("Justine occurs ", occurances_justine, "times in chapter five")
print("Victor occurs ", occurances_victor, "times in chapter five")
print("William occurs ", occurances_william, "times in chapter five")
print ("")

my_file = open("chapter_six.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter six")
print("creature occurs ", occurances_creature, "times in chapter six")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter six")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter six")
print("Ernest occurs ", occurances_ernest, "times in chapter six")
print("Felix occurs ", occurances_felix, "times in chapter six")
print("Henry occurs ", occurances_henry, "times in chapter six")
print("Justine occurs ", occurances_justine, "times in chapter six")
print("Victor occurs ", occurances_victor, "times in chapter six")
print("William occurs ", occurances_william, "times in chapter six")
print ("")

my_file = open("chapter_seven.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter seven")
print("creature occurs ", occurances_creature, "times in chapter seven")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter seven")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter seven")
print("Ernest occurs ", occurances_ernest, "times in chapter seven")
print("Felix occurs ", occurances_felix, "times in chapter seven")
print("Henry occurs ", occurances_henry, "times in chapter seven")
print("Justine occurs ", occurances_justine, "times in chapter seven")
print("Victor occurs ", occurances_victor, "times in chapter seven")
print("William occurs ", occurances_william, "times in chapter seven")
print ("")

my_file = open("chapter_eight.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter eight")
print("creature occurs ", occurances_creature, "times in chapter eight")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter eight")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter eight")
print("Ernest occurs ", occurances_ernest, "times in chapter eight")
print("Felix occurs ", occurances_felix, "times in chapter eight")
print("Henry occurs ", occurances_henry, "times in chapter eight")
print("Justine occurs ", occurances_justine, "times in chapter eight")
print("Victor occurs ", occurances_victor, "times in chapter eight")
print("William occurs ", occurances_william, "times in chapter eight")
print ("")

my_file = open("chapter_nine.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter nine")
print("creature occurs ", occurances_creature, "times in chapter nine")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter nine")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter nine")
print("Ernest occurs ", occurances_ernest, "times in chapter nine")
print("Felix occurs ", occurances_felix, "times in chapter nine")
print("Henry occurs ", occurances_henry, "times in chapter nine")
print("Justine occurs ", occurances_justine, "times in chapter nine")
print("Victor occurs ", occurances_victor, "times in chapter nine")
print("William occurs ", occurances_william, "times in chapter nine")
print ("")

my_file = open("chapter_ten.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter ten")
print("creature occurs ", occurances_creature, "times in chapter ten")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter ten")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter ten")
print("Ernest occurs ", occurances_ernest, "times in chapter ten")
print("Felix occurs ", occurances_felix, "times in chapter ten")
print("Henry occurs ", occurances_henry, "times in chapter ten")
print("Justine occurs ", occurances_justine, "times in chapter ten")
print("Victor occurs ", occurances_victor, "times in chapter tne")
print("William occurs ", occurances_william, "times in chapter ten")
print ("")

my_file = open("chapter_eleven.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter eleven")
print("creature occurs ", occurances_creature, "times in chapter eleven")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter eleven")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter eleven")
print("Ernest occurs ", occurances_ernest, "times in chapter eleven")
print("Felix occurs ", occurances_felix, "times in chapter eleven")
print("Henry occurs ", occurances_henry, "times in chapter eleven")
print("Justine occurs ", occurances_justine, "times in chapter eleven")
print("Victor occurs ", occurances_victor, "times in chapter eleven")
print("William occurs ", occurances_william, "times in chapter eleven")
print ("")

my_file = open("chapter_twelve.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter twelve")
print("creature occurs ", occurances_creature, "times in chapter twelve")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter twelve")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter twelve")
print("Ernest occurs ", occurances_ernest, "times in chapter twelve")
print("Felix occurs ", occurances_felix, "times in chapter twelve")
print("Henry occurs ", occurances_henry, "times in chapter twelve")
print("Justine occurs ", occurances_justine, "times in chapter twelve")
print("Victor occurs ", occurances_victor, "times in chapter twelve")
print("William occurs ", occurances_william, "times in chapter twelve")
print ("")

my_file = open("chapter_thirteen.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter thirteen")
print("creature occurs ", occurances_creature, "times in chapter thirteen")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter thirteen")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter thirteen")
print("Ernest occurs ", occurances_ernest, "times in chapter thirteen")
print("Felix occurs ", occurances_felix, "times in chapter thirteen")
print("Henry occurs ", occurances_henry, "times in chapter thirteen")
print("Justine occurs ", occurances_justine, "times in chapter thirteen")
print("Victor occurs ", occurances_victor, "times in chapter thirteen")
print("William occurs ", occurances_william, "times in chapter thirteen")
print ("")

my_file = open("chapter_fourteen.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter fourteen")
print("creature occurs ", occurances_creature, "times in chapter fourteen")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter fourteen")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter fourteen")
print("Ernest occurs ", occurances_ernest, "times in chapter fourteen")
print("Felix occurs ", occurances_felix, "times in chapter fourteen")
print("Henry occurs ", occurances_henry, "times in chapter fourteen")
print("Justine occurs ", occurances_justine, "times in chapter fourteen")
print("Victor occurs ", occurances_victor, "times in chapter fourteen")
print("William occurs ", occurances_william, "times in chapter fourteen")
print ("")

my_file = open("chapter_fifteen.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter fifteen")
print("creature occurs ", occurances_creature, "times in chapter fifteen")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter fifteen")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter fifteen")
print("Ernest occurs ", occurances_ernest, "times in chapter fifteen")
print("Felix occurs ", occurances_felix, "times in chapter fifteen")
print("Henry occurs ", occurances_henry, "times in chapter fifteen")
print("Justine occurs ", occurances_justine, "times in chapter fifteen")
print("Victor occurs ", occurances_victor, "times in chapter fifteen")
print("William occurs ", occurances_william, "times in chapter fifteen")
print ("")

my_file = open("chapter_sixteen.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter sixteen")
print("creature occurs ", occurances_creature, "times in chapter sixteen")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter sixteen")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter sixteen")
print("Ernest occurs ", occurances_ernest, "times in chapter sixteen")
print("Felix occurs ", occurances_felix, "times in chapter sixteen")
print("Henry occurs ", occurances_henry, "times in chapter sixteen")
print("Justine occurs ", occurances_justine, "times in chapter sixteen")
print("Victor occurs ", occurances_victor, "times in chapter sixteen")
print("William occurs ", occurances_william, "times in chapter sixteen")
print ("")

my_file = open("chapter_seventeen.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter seventeen")
print("creature occurs ", occurances_creature, "times in chapter seventeen")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter seventeen")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter seventeen")
print("Ernest occurs ", occurances_ernest, "times in chapter seventeen")
print("Felix occurs ", occurances_felix, "times in chapter seventeen")
print("Henry occurs ", occurances_henry, "times in chapter seventeen")
print("Justine occurs ", occurances_justine, "times in chapter seventeen")
print("Victor occurs ", occurances_victor, "times in chapter seventeen")
print("William occurs ", occurances_william, "times in chapter seventeen")
print ("")

my_file = open("chapter_eighteen.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter eighteen")
print("creature occurs ", occurances_creature, "times in chapter eighteen")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter eighteen")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter eighteen")
print("Ernest occurs ", occurances_ernest, "times in chapter eighteen")
print("Felix occurs ", occurances_felix, "times in chapter eighteen")
print("Henry occurs ", occurances_henry, "times in chapter eighteen")
print("Justine occurs ", occurances_justine, "times in chapter eighteen")
print("Victor occurs ", occurances_victor, "times in chapter eighteen")
print("William occurs ", occurances_william, "times in chapter eighteen")
print ("")

my_file = open("chapter_ninteen.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter ninteen")
print("creature occurs ", occurances_creature, "times in chapter ninteen")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter ninteen")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter ninteen")
print("Ernest occurs ", occurances_ernest, "times in chapter ninteen")
print("Felix occurs ", occurances_felix, "times in chapter ninteen")
print("Henry occurs ", occurances_henry, "times in chapter ninteen")
print("Justine occurs ", occurances_justine, "times in chapter ninteen")
print("Victor occurs ", occurances_victor, "times in chapter ninteen")
print("William occurs ", occurances_william, "times in chapter ninteen")
print ("")

my_file = open("chapter_twenty.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter twenty")
print("creature occurs ", occurances_creature, "times in chapter twenty")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter twenty")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter twenty")
print("Ernest occurs ", occurances_ernest, "times in chapter twenty")
print("Felix occurs ", occurances_felix, "times in chapter twenty")
print("Henry occurs ", occurances_henry, "times in chapter twenty")
print("Justine occurs ", occurances_justine, "times in chapter twenty")
print("Victor occurs ", occurances_victor, "times in chapter twenty")
print("William occurs ", occurances_william, "times in chapter twenty")
print ("")

my_file = open("chapter_twentyone.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter twenty-one")
print("creature occurs ", occurances_creature, "times in chapter twenty-one")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter twenty-one")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter twenty-one")
print("Ernest occurs ", occurances_ernest, "times in chapter twenty-one")
print("Felix occurs ", occurances_felix, "times in chapter twenty-one")
print("Henry occurs ", occurances_henry, "times in chapter twenty-one")
print("Justine occurs ", occurances_justine, "times in chapter twenty-one")
print("Victor occurs ", occurances_victor, "times in chapter twenty-one")
print("William occurs ", occurances_william, "times in chapter twenty-one")
print ("")

my_file = open("chapter_twentytwo.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter twenty-two")
print("creature occurs ", occurances_creature, "times in chapter twenty-two")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter twenty-two")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter twenty-two")
print("Ernest occurs ", occurances_ernest, "times in chapter twenty-two")
print("Felix occurs ", occurances_felix, "times in chapter twenty-two")
print("Henry occurs ", occurances_henry, "times in chapter twenty-two")
print("Justine occurs ", occurances_justine, "times in chapter twenty-two")
print("Victor occurs ", occurances_victor, "times in chapter twenty-two")
print("William occurs ", occurances_william, "times in chapter twenty-two")
print ("")


my_file = open("chapter_twentythree.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter twenty-three")
print("creature occurs ", occurances_creature, "times in chapter twenty-three")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter twenty-three")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter twenty-three")
print("Ernest occurs ", occurances_ernest, "times in chapter twenty-three")
print("Felix occurs ", occurances_felix, "times in chapter twenty-three")
print("Henry occurs ", occurances_henry, "times in chapter twenty-three")
print("Justine occurs ", occurances_justine, "times in chapter twenty-three")
print("Victor occurs ", occurances_victor, "times in chapter twenty-three")
print("William occurs ", occurances_william, "times in chapter twenty-three")
print ("")

my_file = open("chapter_twentyfour.txt", "r")
data = my_file.read()
word = data.split()

occurances_victor = data.count("Victor")
occurances_creature = data.count("creature")
occurances_agatha = data.count("Agatha")
occurances_delacy = data.count("De Lacey")
occurances_elizabeth = data.count("Elizabeth")
occurances_ernest = data.count("Ernest")
occurances_felix = data.count("Felix")
occurances_henry = data.count("Henry")
occurances_justine = data.count("Justine")
occurances_william = data.count("William")

print("Agatha occurs ", occurances_agatha, "times in chapter twenty-four")
print("creature occurs ", occurances_creature, "times in chapter twenty-four")
print("Old Man De Lacey occurs ", occurances_delacy, "times in chapter twenty-four")
print("Elizabeth occurs ", occurances_elizabeth, "times in chapter twenty-four")
print("Ernest occurs ", occurances_ernest, "times in chapter twenty-four")
print("Felix occurs ", occurances_felix, "times in chapter twenty-four")
print("Henry occurs ", occurances_henry, "times in chapter twenty-four")
print("Justine occurs ", occurances_justine, "times in chapter twenty-four")
print("Victor occurs ", occurances_victor, "times in chapter twenty-four")
print("William occurs ", occurances_william, "times in chapter twenty-four")
print ("")




fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
characters = ['Victor', 'Creature', 'Agataha', 'De Lacey', 'Elizabeth', 'Ernest', 'Felix', 'Henry', 'Justine', 'William']
appearences = [28,69,22,9,92,13,50,26,55,25]
ax.bar(characters,appearences)
ax.set_ylabel('Nimber of occurances')
ax.set_title('Number of times each character name occures in Frankenstein book')
plt.show()

print('book connection: I know Victor Frankenstein is the scientist who creates the creature. '
      'based off the character breakdown I would say te creature is created in chapter five because '
      'that is when we see his name appear. Justine is mentioned a lot in the middle of the book'
      'and then never again so maybe she passed away or moved away. Whenever Ellizabeth appears'
      'a lot in a chapter, so does Victor, so they are probably connected somehow- marriange maybe? '
      'Felix, Agatha, and De Lacey appear a lot together too so they are also probably related'
      ' and they appear a lof with the creature so they must have some involvment with him too')




